In [ ]:
import pandas as pd

In [ ]:
# Opening A local csv file

df=pd.read_csv('/content/college_sleep_and_gpa.csv')

In [ ]:
# 3. Opening a csv file from an URL

import requests
from io import StringIO

url=""
headers={"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req=requests.get(url,headers=headers)
data=StringIO(req.text)

pd.read_csv(data)

In [ ]:
pd.read_csv('/content/college_sleep_and_gpa.csv')

,student_id,study,university,semester,cohort_code,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,...,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,gpa_change,term_units,term_load_z,under_6h_sleep,sleep_bracket,sleep_midpoint_clock
0,293,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,370.0,6.17,...,0.0500,0.931,4.00,3.76,-0.24,49.0,0.112,0,6-6.5h,07:20
1,294,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,...,0.0476,0.862,4.00,3.55,-0.45,49.0,0.112,0,6.5-7h,05:00
2,297,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,...,0.1639,0.586,3.00,3.59,0.59,46.0,-0.604,1,<5.5h,05:38
3,303,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,...,0.7854,0.931,3.80,3.46,-0.34,39.0,-2.275,0,6.5-7h,07:52
4,304,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,408.1,6.80,...,0.1538,0.931,3.17,3.50,0.33,39.0,-2.275,0,6.5-7h,04:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,347,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,445.6,7.43,...,0.0950,1.000,3.74,3.74,0.00,46.0,-0.663,0,7-7.5h,04:13
630,349,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,430.8,7.18,...,0.1070,0.276,3.44,3.61,0.17,49.0,-0.139,0,7-7.5h,04:51
631,353,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,360.9,6.01,...,0.0608,1.000,3.62,3.81,0.19,54.0,0.735,0,6-6.5h,06:33
632,356,5,Carnegie Mellon University,Spring 2017,lac1,Male,0.0,0.0,303.8,5.06,...,0.1568,0.276,3.22,1.38,-1.84,48.0,-0.313,1,<5.5h,06:11
633,357,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,397.9,6.63,...,0.2347,0.897,4.00,4.00,0.00,49.0,-0.139,0,6.5-7h,05:48

In [ ]:
pd.read_csv('/content/college_sleep_and_gpa.csv',index_col='student_id')

,study,university,semester,cohort_code,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,daytime_sleep_minutes,...,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,gpa_change,term_units,term_load_z,under_6h_sleep,sleep_bracket,sleep_midpoint_clock
student_id,,,,,,,,,,,,,,,,,,,,,
293,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,370.0,6.17,11.7,...,0.0500,0.931,4.00,3.76,-0.24,49.0,0.112,0,6-6.5h,07:20
294,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,49.7,...,0.0476,0.862,4.00,3.55,-0.45,49.0,0.112,0,6.5-7h,05:00
297,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,178.5,...,0.1639,0.586,3.00,3.59,0.59,46.0,-0.604,1,<5.5h,05:38
303,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,26.1,...,0.7854,0.931,3.80,3.46,-0.34,39.0,-2.275,0,6.5-7h,07:52
304,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,408.1,6.80,71.6,...,0.1538,0.931,3.17,3.50,0.33,39.0,-2.275,0,6.5-7h,04:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,445.6,7.43,31.9,...,0.0950,1.000,3.74,3.74,0.00,46.0,-0.663,0,7-7.5h,04:13
349,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,430.8,7.18,18.6,...,0.1070,0.276,3.44,3.61,0.17,49.0,-0.139,0,7-7.5h,04:51
353,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,360.9,6.01,22.1,...,0.0608,1.000,3.62,3.81,0.19,54.0,0.735,0,6-6.5h,06:33
356,5,Carnegie Mellon University,Spring 2017,lac1,Male,0.0,0.0,303.8,5.06,11.9,...,0.1568,0.276,3.22,1.38,-1.84,48.0,-0.313,1,<5.5h,06:11
357,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,397.9,6.63,22.7,...,0.2347,0.897,4.00,4.00,0.00,49.0,-0.139,0,6.5-7h,05:48

In [ ]:
# 7. use_cols parameter

pd.read_csv('/content/college_sleep_and_gpa.csv',usecols=['student_id','cohort_code','gender'])

     student_id cohort_code  gender
0           293        lac2  Female
1           294        lac2  Female
2           297        lac2  Female
3           303        lac2  Female
4           304        lac2  Female
..          ...         ...     ...
629         347        lac1  Female
630         349        lac1  Female
631         353        lac1  Female
632         356        lac1    Male
633         357        lac1  Female

[634 rows x 3 columns]

In [ ]:
# 8. Squeeze parametes

pd.read_csv('/content/college_sleep_and_gpa.csv',usecols=['student_id'])

     student_id
0           293
1           294
2           297
3           303
4           304
..          ...
629         347
630         349
631         353
632         356
633         357

[634 rows x 1 columns]

In [ ]:
# 9. SkipRows /nrows Parameter
pd.read_csv('/content/college_sleep_and_gpa.csv',skiprows=[0,5])

,293,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0.1,370.0,6.17,...,0.05,0.931,4.0,3.76,-0.24,49.0,0.112,0,6-6.5h,07:20
0,294,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,...,0.0476,0.862,4.00,3.55,-0.45,49.0,0.112,0,6.5-7h,05:00
1,297,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,...,0.1639,0.586,3.00,3.59,0.59,46.0,-0.604,1,<5.5h,05:38
2,303,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,...,0.7854,0.931,3.80,3.46,-0.34,39.0,-2.275,0,6.5-7h,07:52
3,305,1,Carnegie Mellon University,Spring 2018,lac2,Male,1.0,1.0,346.8,5.78,...,1.0689,0.724,2.37,2.54,0.17,49.0,0.112,1,5.5-6h,08:01
4,306,1,Carnegie Mellon University,Spring 2018,lac2,Male,0.0,0.0,340.0,5.67,...,0.6244,0.759,3.40,3.50,0.10,45.0,-0.843,1,5.5-6h,07:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,347,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,445.6,7.43,...,0.0950,1.000,3.74,3.74,0.00,46.0,-0.663,0,7-7.5h,04:13
628,349,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,430.8,7.18,...,0.1070,0.276,3.44,3.61,0.17,49.0,-0.139,0,7-7.5h,04:51
629,353,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,360.9,6.01,...,0.0608,1.000,3.62,3.81,0.19,54.0,0.735,0,6-6.5h,06:33
630,356,5,Carnegie Mellon University,Spring 2017,lac1,Male,0.0,0.0,303.8,5.06,...,0.1568,0.276,3.22,1.38,-1.84,48.0,-0.313,1,<5.5h,06:11
631,357,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,397.9,6.63,...,0.2347,0.897,4.00,4.00,0.00,49.0,-0.139,0,6.5-7h,05:48

In [ ]:
pd.read_csv('/content/college_sleep_and_gpa.csv',nrows=100)

,student_id,study,university,semester,cohort_code,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,...,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,gpa_change,term_units,term_load_z,under_6h_sleep,sleep_bracket,sleep_midpoint_clock
0,293,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,370.0,6.17,...,0.0500,0.931,4.000,3.760,-0.240,49.0,0.112,0,6-6.5h,07:20
1,294,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,...,0.0476,0.862,4.000,3.550,-0.450,49.0,0.112,0,6.5-7h,05:00
2,297,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,...,0.1639,0.586,3.000,3.590,0.590,46.0,-0.604,1,<5.5h,05:38
3,303,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,...,0.7854,0.931,3.800,3.460,-0.340,39.0,-2.275,0,6.5-7h,07:52
4,304,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,408.1,6.80,...,0.1538,0.931,3.170,3.500,0.330,39.0,-2.275,0,6.5-7h,04:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,31,2,University of Washington,Spring 2018,uw1,Female,0.0,0.0,459.5,7.66,...,0.0833,0.964,4.000,4.000,0.000,13.0,-0.498,0,7.5h+,03:41
96,32,2,University of Washington,Spring 2018,uw1,Female,1.0,0.0,405.2,6.75,...,0.0622,1.000,3.180,3.500,0.320,10.0,-1.805,0,6.5-7h,05:03
97,33,2,University of Washington,Spring 2018,uw1,Female,1.0,0.0,396.5,6.61,...,0.1101,1.000,2.567,2.992,0.426,13.0,-0.498,0,6.5-7h,05:51
98,34,2,University of Washington,Spring 2018,uw1,Female,1.0,0.0,389.0,6.48,...,0.2066,0.536,3.741,3.479,-0.262,14.0,-0.062,0,6-6.5h,04:00
99,35,2,University of Washington,Spring 2018,uw1,Female,0.0,0.0,441.0,7.35,...,0.3075,1.000,3.532,3.600,0.068,15.0,0.373,0,7-7.5h,04:45

In [ ]:
# dtype parameter
pd.read_csv('/content/college_sleep_and_gpa.csv',dtype={'first_generation':float })

,student_id,study,university,semester,cohort_code,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,...,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,gpa_change,term_units,term_load_z,under_6h_sleep,sleep_bracket,sleep_midpoint_clock
0,293,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,370.0,6.17,...,0.0500,0.931,4.00,3.76,-0.24,49.0,0.112,0,6-6.5h,07:20
1,294,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,...,0.0476,0.862,4.00,3.55,-0.45,49.0,0.112,0,6.5-7h,05:00
2,297,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,...,0.1639,0.586,3.00,3.59,0.59,46.0,-0.604,1,<5.5h,05:38
3,303,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,...,0.7854,0.931,3.80,3.46,-0.34,39.0,-2.275,0,6.5-7h,07:52
4,304,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,408.1,6.80,...,0.1538,0.931,3.17,3.50,0.33,39.0,-2.275,0,6.5-7h,04:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,347,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,445.6,7.43,...,0.0950,1.000,3.74,3.74,0.00,46.0,-0.663,0,7-7.5h,04:13
630,349,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,430.8,7.18,...,0.1070,0.276,3.44,3.61,0.17,49.0,-0.139,0,7-7.5h,04:51
631,353,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,360.9,6.01,...,0.0608,1.000,3.62,3.81,0.19,54.0,0.735,0,6-6.5h,06:33
632,356,5,Carnegie Mellon University,Spring 2017,lac1,Male,0.0,0.0,303.8,5.06,...,0.1568,0.276,3.22,1.38,-1.84,48.0,-0.313,1,<5.5h,06:11
633,357,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,397.9,6.63,...,0.2347,0.897,4.00,4.00,0.00,49.0,-0.139,0,6.5-7h,05:48

In [ ]:
# 13. Handling Dates
pd.read_csv('/content/college_sleep_and_gpa.csv',parse_dates=['semester']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               634 non-null    int64
 1   study                    634 non-null    int64
 2   university               634 non-null    object
 3   semester                 634 non-null    object
 4   cohort_code              634 non-null    object
 5   gender                   631 non-null    object
 6   first_generation         630 non-null    float64
 7   underrepresented         633 non-null    float64
 8   avg_sleep_minutes        634 non-null    float64
 9   avg_sleep_hours          634 non-null    float64
 10  daytime_sleep_minutes    634 non-null    float64
 11  sleep_midpoint_minutes   634 non-null    float64
 12  bedtime_variability      634 non-null    float64
 13  nights_tracked_fraction  634 non-null    float64
 14  prior_gpa                634 non-null    float64
 15  term_gpa                 634 non-null    float64
 16  gpa_change               634 non-null    float64
 17  term_units               487 non-null    float64
 18  term_load_z              487 non-null    float64
 19  under_6h_sleep           634 non-null    int64
 20  sleep_bracket            634 non-null    object
 21  sleep_midpoint_clock     634 non-null    object
dtypes: float64(13), int64(3), object(6)
memory usage: 109.1+ KB

/tmp/ipykernel_3548/3714631885.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('/content/college_sleep_and_gpa.csv',parse_dates=['semester']).info()

In [ ]:
# 14. Convertors

pd.read_csv('/content/college_sleep_and_gpa.csv',converters={'student_id':str}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               634 non-null    object
 1   study                    634 non-null    int64
 2   university               634 non-null    object
 3   semester                 634 non-null    object
 4   cohort_code              634 non-null    object
 5   gender                   631 non-null    object
 6   first_generation         630 non-null    float64
 7   underrepresented         633 non-null    float64
 8   avg_sleep_minutes        634 non-null    float64
 9   avg_sleep_hours          634 non-null    float64
 10  daytime_sleep_minutes    634 non-null    float64
 11  sleep_midpoint_minutes   634 non-null    float64
 12  bedtime_variability      634 non-null    float64
 13  nights_tracked_fraction  634 non-null    float64
 14  prior_gpa                634 non-null    float64
 15  term_gpa                 634 non-null    float64
 16  gpa_change               634 non-null    float64
 17  term_units               487 non-null    float64
 18  term_load_z              487 non-null    float64
 19  under_6h_sleep           634 non-null    int64
 20  sleep_bracket            634 non-null    object
 21  sleep_midpoint_clock     634 non-null    object
dtypes: float64(13), int64(2), object(7)
memory usage: 109.1+ KB

In [ ]:
def rename(name):
  if name=="Carnegie Mellon University":
    return "CMU"
  else:
    return name

In [ ]:
rename("Carnegie Mellon University")

'CMU'

In [ ]:
# Convertors

pd.read_csv('/content/college_sleep_and_gpa.csv',converters={'university':rename})

,student_id,study,university,semester,cohort_code,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,...,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,gpa_change,term_units,term_load_z,under_6h_sleep,sleep_bracket,sleep_midpoint_clock
0,293,1,CMU,Spring 2018,lac2,Female,0.0,0.0,370.0,6.17,...,0.0500,0.931,4.00,3.76,-0.24,49.0,0.112,0,6-6.5h,07:20
1,294,1,CMU,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,...,0.0476,0.862,4.00,3.55,-0.45,49.0,0.112,0,6.5-7h,05:00
2,297,1,CMU,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,...,0.1639,0.586,3.00,3.59,0.59,46.0,-0.604,1,<5.5h,05:38
3,303,1,CMU,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,...,0.7854,0.931,3.80,3.46,-0.34,39.0,-2.275,0,6.5-7h,07:52
4,304,1,CMU,Spring 2018,lac2,Female,0.0,1.0,408.1,6.80,...,0.1538,0.931,3.17,3.50,0.33,39.0,-2.275,0,6.5-7h,04:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,347,5,CMU,Spring 2017,lac1,Female,0.0,0.0,445.6,7.43,...,0.0950,1.000,3.74,3.74,0.00,46.0,-0.663,0,7-7.5h,04:13
630,349,5,CMU,Spring 2017,lac1,Female,0.0,0.0,430.8,7.18,...,0.1070,0.276,3.44,3.61,0.17,49.0,-0.139,0,7-7.5h,04:51
631,353,5,CMU,Spring 2017,lac1,Female,0.0,0.0,360.9,6.01,...,0.0608,1.000,3.62,3.81,0.19,54.0,0.735,0,6-6.5h,06:33
632,356,5,CMU,Spring 2017,lac1,Male,0.0,0.0,303.8,5.06,...,0.1568,0.276,3.22,1.38,-1.84,48.0,-0.313,1,<5.5h,06:11
633,357,5,CMU,Spring 2017,lac1,Female,0.0,0.0,397.9,6.63,...,0.2347,0.897,4.00,4.00,0.00,49.0,-0.139,0,6.5-7h,05:48

In [ ]:
# 15. na_values parameter
pd.read_csv('/content/college_sleep_and_gpa.csv',na_values=['Male'])

,student_id,study,university,semester,cohort_code,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,...,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,gpa_change,term_units,term_load_z,under_6h_sleep,sleep_bracket,sleep_midpoint_clock
0,293,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,370.0,6.17,...,0.0500,0.931,4.00,3.76,-0.24,49.0,0.112,0,6-6.5h,07:20
1,294,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,...,0.0476,0.862,4.00,3.55,-0.45,49.0,0.112,0,6.5-7h,05:00
2,297,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,...,0.1639,0.586,3.00,3.59,0.59,46.0,-0.604,1,<5.5h,05:38
3,303,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,...,0.7854,0.931,3.80,3.46,-0.34,39.0,-2.275,0,6.5-7h,07:52
4,304,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,408.1,6.80,...,0.1538,0.931,3.17,3.50,0.33,39.0,-2.275,0,6.5-7h,04:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,347,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,445.6,7.43,...,0.0950,1.000,3.74,3.74,0.00,46.0,-0.663,0,7-7.5h,04:13
630,349,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,430.8,7.18,...,0.1070,0.276,3.44,3.61,0.17,49.0,-0.139,0,7-7.5h,04:51
631,353,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,360.9,6.01,...,0.0608,1.000,3.62,3.81,0.19,54.0,0.735,0,6-6.5h,06:33
632,356,5,Carnegie Mellon University,Spring 2017,lac1,NaN,0.0,0.0,303.8,5.06,...,0.1568,0.276,3.22,1.38,-1.84,48.0,-0.313,1,<5.5h,06:11
633,357,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,397.9,6.63,...,0.2347,0.897,4.00,4.00,0.00,49.0,-0.139,0,6.5-7h,05:48

In [ ]:
# 16. Loading a huge dataset in chunks
dfs=pd.read_csv('/content/college_sleep_and_gpa.csv',chunksize=100)

In [ ]:
for chunks in dfs:
  print(chunks.shape)

(100, 22)
(100, 22)
(100, 22)
(100, 22)
(34, 22)